### ISSUE TITLE
QiskitUnityAsset

### ISSUE THREAD

**Issue by boland25** [HuangJunye/QPong-Unity#1]
[https://github.com/asierarranz/QiskitUnityAsset](https://github.com/asierarranz/QiskitUnityAsset)

This is still a work in progress, they need a few more days to complete.  But here it is and see if you can use it

**Comment by HuangJunye** [comment]
I implemented the first version in QPong Unity. The strings are sent using WebForm data. Perhaps there is performance advantage to change to JSON. We can worry about the performance once the game is almost finished.
