### ISSUE TITLE
On what platform do we want to put this game?

### ISSUE THREAD

**Issue by HuangJunye** [HuangJunye/QPong-Unity#12]
The first platform will be arcade machines, because it is the closest to the original Pong game and it is really cool to play a game on an arcade machine! Shall we consider any platform beyond arcade machine? Perhaps mobile phone?

**Comment by boland25** [comment]
@HuangJunye we can build it for any device we want with the unity platform.  We will have it running on Windows because that is what our arcade machine is running, but its easy to also build for mac.  Touchscreens would be a little more difficult to figure out the mechanics of play

**Comment by HuangJunye** [comment]
Would be cool to play it on a console too. Not sure how difficult it is to release a game on PlayStation/Xbox/Switch. Anyway, I realise it’s too early to think about making it to other platforms. Let’s focus on the arcade version.

**Comment by boland25** [comment]
consoles would be easy because the input would already be handled, just have to make sure you have the buttons mapped accordingly.  But yes agreed, lets see how the arcade version is received first

**Comment by HuangJunye** [comment]
That’s right. I was thinking about releasing on the online stores of the consoles but i was probably just daydreaming haha.
