### ISSUE TITLE
Sound effects discussion

### ISSUE THREAD

**Issue by HuangJunye** [HuangJunye/QPong-Unity#18]
The sound effects should follow similar direction as the visual effects:
Make the game as similar to the original as possible. But the moment quantumness comes in, it goes wild.

**Comment by HuangJunye** [comment]
I can think about several sounds
1. Classical paddle bounce sound: as close to original as possible
1. Non-superposed quantum paddle (only X gate involved) bounce sound: same as classical paddle bounce sound. Or perhaps we can tune a little bit.
1. Superposed quantum paddle (H gate involved) bounce sound: some cool sound, depending on the states?
1. Normal ball bounce from the wall: as close to original as possible
1. Superposed ball bounce from the wall: some cool sound, depending on the states?
1. Measurement sound: sound of collapsing (as the states are collapsed after measurement).

**Comment by boland25** [comment]
@HuangJunye I actually have obtained a few classic sounds and was planning on adding them into the game either this or next week.  The quantum sounds could be really interesting, that will take some work, maybe I can source them from an actual machine?

**Comment by HuangJunye** [comment]
What kind of sound can source from a quantum computer? I was thinking about sounds generated using James’ Quantum Toy Piano (https://github.com/JavaFXpert/quantum-toy-piano-ibmq)

**Comment by boland25** [comment]
@HuangJunye well I think i can get some pulse sounds out of it, but I am not sure if I will get the permissions

**Comment by boland25** [comment]
@HuangJunye also in the meantime i added some sound effects I found that should help us try and re-create classic sounds.  Have a look in the branch `feature/newSounds`

**Comment by HuangJunye** [comment]
Added sound effect in PR #26  and PR #28
