### ISSUE TITLE
Communication between Unity and Qiskit is too slow

### ISSUE THREAD

**Issue by HuangJunye** [HuangJunye/QPong-Unity#20]
The time it takes to send gate array, generate quantum circuit in python server and return state vector is too long. It affects the gameplay experience. What can we do to reduce the lag?

**Comment by HuangJunye** [comment]
Find out the cause of lag. Is it because the length of gate array strings? Check if the lag is reduced when gate depth is reduced to 3 (we will use 3x3 circuit only).

**Comment by boland25** [comment]
Is the lag on the communication between unity and api?  Or is it in the processing of the circuit in the simulator?

**Comment by HuangJunye** [comment]
I am not 100% sure. I played the python version two days ago and it felt much smoother. So the lag is likely on the processing of the circuit.

**Comment by HuangJunye** [comment]
The lag is not very noticeable any more.
