### ISSUE TITLE
Game controller

### ISSUE THREAD

**Issue by filemaster** [HuangJunye/QPong-Unity#32]
Create a Game Controller to:

- Control scene changes
- Move data between different scenes
- Control data storage (if required)

**Comment by HuangJunye** [comment]
I am going to add start menu, game over scene and ranking in the `feature/newUI` branch

**Comment by HuangJunye** [comment]
I realised I may not have time to do this today. Please go ahead to create placeholder scenes if needed. I will work on it tomorrow.

**Comment by filemaster** [comment]
Closed #37
