### ISSUE TITLE
Restart game

### ISSUE THREAD

**Issue by filemaster** [HuangJunye/QPong-Unity#36]
I saw there is an option to restart the game while playing. 

In my oppinion this button must not exist since we are creating an arcade machine. Usual behaviour is to show the 'game over ' text and back to main menu. 

@boland25, Can I modify this? Or do you think is important to keep it as it is now?

**Comment by HuangJunye** [comment]
@filemaster Please remove the button. It’s there only because I followed a beginner tutorial of making Pong game in unity.

**Comment by filemaster** [comment]
👍🏻
