### ISSUE TITLE
Transition to EndGame and restart the game

### ISSUE THREAD

**Issue by HuangJunye** [HuangJunye/QPong-Unity#39]
I want to add transition to EndGame scene and from there press any key to restart the game. To restart the game, I need to reset the score and circuit. I see @filemaster added RestartGame in GameManager.cs, but I have problem accessing to gameManager once I go to the EndGame scene. Should I add DontDestroyOnLoad(transform.gameObject) to GameManager.cs?

**Comment by HuangJunye** [comment]
In the EndGame scene, we should ask player to input their name for the ranking.

**Comment by boland25** [comment]
GameController is a singelton instance so you should be able to get at it everywhere by saying 
`GameController.Instance.methodYouWantToCall()`

**Comment by boland25** [comment]
and yes entering player initials is a good one.  we need that for hello quantum too, so maybe assigm that to @filemaster as an issue

**Comment by HuangJunye** [comment]
I can access GameController but the restart method is under GameManager. At the end I release only thing I need to reset is the player score and it can be accessed in GameController. I made the commit for that.

**Comment by filemaster** [comment]
@HuangJunye I will do it. GameManager is instantiated every time the game scene is loaded, so all its variables will be reset automatically.
