### ISSUE TITLE
setup the python structure so that it can be run from the command line

### ISSUE THREAD

**Issue by boland25** [HuangJunye/QPong-Unity#5]
Currently there is some sort of directory pathing that is happening in PYCharm that does not seem to be working when you open a terminal and type `python3 server.py`.  We get module not found commands.  The easy fix is to pull the server.py out of the flask_server folder and move it to the root.  Or move the models folder into the flask_server structure so its in the python hierarchy instead of side by side.

**Comment by HuangJunye** [comment]
Solved by PR Bugfix/fix python server #21
