### ISSUE TITLE
Slow communication to local python server in Mac build

### ISSUE THREAD

**Issue by HuangJunye** [HuangJunye/QPong-Unity#52]
I made a Mac build for mini-arcade. The quantum paddles take more than 1s to respond for X gate, and they don’t respond to H gate. No problem found when game is played inside Unity engine. 

@boland25 @filemaster Any idea how to solve this issue?

**Comment by filemaster** [comment]
Fixed #58

**Comment by HuangJunye** [comment]
@filemaster Thank you so much Ivan! You are amazing!
